language: ruby
rvm:
  - 2.1.5

branches:
  only:
    - master

cache: bundler

addons:
  postgresql: 9.4



before_script:
  - export CODECLIMATE_REPO_TOKEN=b6ec51f957799b34684a898d2229582b0d019a2c63da630b1c024421cf10569d bundle exec rake
  - psql -c 'create database angular_on_rails_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"

script: bundle exec rspec spec/

